apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-{{ .Values.role }}
  labels:
    app.kubernetes.io/name: locust-{{ .Values.role }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: locust-{{ .Values.role }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: locust-{{ .Values.role }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: locust-{{ .Values.role }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOCUST_MODE
              value: {{ .Values.role }}
            - name: TARGET_HOST
              value: {{ .Values.target_host }}
            - name: LOCUST_MASTER
              value: locust-master
          {{if eq .Values.role "master" }}
          ports:
          {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
          {{ end }}
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
