apiVersion: v1
kind: Service
metadata:
  name: openapi-service
  labels:
    {{- include "phoenix-openapi-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
