{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phoenix-wx.serviceAccountName" . }}
  labels:
{{ include "phoenix-wx.labels" . | nindent 4 }}
{{- end -}}
